/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "events": {
        "ERRORS": {
            "UNAUTHORIZED": string;
            "FORBIDDEN": string;
            "INTERNAL_SERVER_ERROR": string;
            "USER": {
                "NOT_FOUND": string;
                "CONFLICT_EMAIL": string;
                "CONFLICT_USERNAME": string;
            };
            "TOKEN": {
                "ALREADY_USED": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
